Repository Another-Glass/Assignment6_Team, pull requests merged in 2021-11, with the labels that each got.

#9 [feat]: 할인 계산 체인 로직 추가
  src/libs/costChains/costCalculator.js
  src/libs/costChains/discountChain.js
Labels: :fire: Feat

#10 [feat]: 반납금지여부 벌금 부과 코드 추가
  src/libs/costChains/discountChain.js
  src/libs/costChains/forbiddenAreaFineChain.js
Labels: :fire: Feat

#12 [feat]: 기본가격 계산 체인 and 필요 서비스 구현
  src/libs/costChains/defaultCostChain.js
  src/services/defaultCostService.js
Labels: :fire: Feat

#13 [feat]: 지역범위 초과 벌금 계산 코드 추가
  src/libs/costChains/outOfAreaFineChain.js
Labels: :fire: Feat

#14 [fix]: goToNextChain await 추가
  src/libs/costChains/discountChain.js
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/outOfAreaFineChain.js
Labels: :hammer_and_wrench: Fix

#15 [feat]: 책임연쇄패턴 설계 완성
  src/app.js
  src/controllers/historyController.js
  src/libs/costChains/costCalculator.js
  src/libs/costChains/costChainBase.js
  src/libs/costChains/index.js
  src/services/deerService.js
  src/services/historyService.js
Labels: :fire: Feat

#16 [feat]: 1분 이내 무료 체인 구현 및 리턴값 수정
  src/libs/costChains/defaultCostChain.js
  src/libs/costChains/freeChain.js
Labels: :fire: Feat

#18 [fix]: 체이닝 관련 버그 및 로그 추가
  src/controllers/historyController.js
  src/libs/costChains/costCalculator.js
  src/libs/costChains/costChainBase.js
  src/libs/costChains/defaultCostChain.js
  src/libs/costChains/index.js
Labels: :hammer_and_wrench: Fix

#19 [HOTFIX]: 지역범위 초과, 반납금지, 할인 계산 chain에 try, catch문 추가
  src/libs/costChains/discountChain.js
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/outOfAreaFineChain.js
Labels: :hammer_and_wrench: Fix

#20 [HOTFIX]: chains 이름 변경
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/outOfAreaFineChain.js
Labels: :hammer_and_wrench: Fix

#21 [feat]: 환승 할인 체인 구현 및 일부 코드 수정
  src/libs/costChains/defaultCostChain.js
  src/libs/costChains/fineChain.js
  src/libs/costChains/freeChain.js
  src/libs/costChains/transportChain.js
Labels: :fire: Feat, :hammer_and_wrench: Fix

#22 [fix]: api 응답값 수정 및 코드스타일 정리
  src/controllers/historyController.js
  src/libs/costChains/costCalculator.js
  src/libs/costChains/costChainBase.js
  src/libs/costChains/index.js
  src/services/deerService.js
Labels: :hammer_and_wrench: Fix

#23 [fix]: defaultChain 코드 수정
  src/libs/costChains/defaultCostChain.js
Labels: :hammer_and_wrench: Fix

#26 [HOTFIX]: 할인 계산, 반납 금지, 지역 범위 초과 체이닝 버그 수정
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/index.js
  src/libs/costChains/outOfAreaFineChain.js
  src/libs/costChains/parkingDiscountChain.js
Labels: :hammer_and_wrench: Fix

#29 [HOTFIX]: 할인 계산, 반납 금지, 지역 범위 체이닝 로직 수정
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/outOfAreaFineChain.js
  src/libs/costChains/parkingDiscountChain.js
Labels: :hammer_and_wrench: Fix

#30 [fix]:목록조회 api들 라우터 수정
  src/app.js
  src/globals/routes.js
  src/libs/costChains/costCalculator.js
  src/libs/costChains/costChainBase.js
  src/routes/globalRouter.js
  src/routes/listingRouter.js
Labels: :hammer_and_wrench: Fix

#31 [test]: 테스트 후 오류 사항 수정 및 구조 변경
  src/libs/costChains/defaultCostChain.js
  src/libs/costChains/freeChain.js
  src/libs/costChains/index.js
  src/libs/costChains/transportChain.js
  src/services/areaService.js
  src/services/defaultCostService.js
  src/services/historyService.js
Labels: :hammer_and_wrench: Fix

#32 [HOTFIX]: 체인 서비스 로직 리턴 값 파싱 수정
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/parkingDiscountChain.js
Labels: :hammer_and_wrench: Fix

#34 [fix]: 체인 상수값 env에 추가
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/outOfAreaFineChain.js
  src/libs/costChains/parkingDiscountChain.js
Labels: :hammer_and_wrench: Fix

#35 [fix]: freeChain, transportChain 수정 및 체인연결
  src/libs/costChains/freeChain.js
  src/libs/costChains/index.js
  src/libs/costChains/transportChain.js
Labels: :hammer_and_wrench: Fix

#36 [fix]: 체인 계산 별 타입 수정
  src/libs/costChains/forbiddenAreaFineChain.js
  src/libs/costChains/freeChain.js
  src/libs/costChains/outOfAreaFineChain.js
  src/libs/costChains/parkingDiscountChain.js
Labels: :hammer_and_wrench: Fix

#38 [refac]: 체인 리팩토링
  src/libs/costCalculator/CostChainBase.js
Labels: :hammer_and_wrench: Fix

#40 리드미 완성
  README.md
  src/test/data/dto/postAccount.json
  src/test/data/dto/signup.json
  src/test/data/dto/token.json
  src/test/unit/controllers/accountController/postAccount.test.js
  src/test/unit/controllers/transactionController/getTransaction.test.js
  src/test/unit/controllers/transactionController/postTransaction.test.js
  src/test/unit/controllers/userController/postToken.test.js
  src/test/unit/controllers/userController/postUser.test.js
Labels: :book: Documentation
